### ISSUE TITLE
Better index

### ISSUE THREAD

**Issue by ouuan** [pcovellite/problem#1]
I have several plans:

1.  Keep the index branch, and move the titles to `<problem branch>:problem.yml`, so that there's only an array of IDs in `index.json`.

2.  Remove all branches and only keep the problem branches, and the index is not needed.

3.  Remove the index branch but keep the master branch for the README, and (one of them):
    1. Let problem branches have a prefix like `problem/go0001`.
    2. Forbid a problem ID to be `master`.

I think the plan 2 is the best :thinking: We can put the README for the project elsewhere, and put a short description in the repo description.

**Comment by diauweb** [comment]
The propose of index branch is to get all titles together. We can't request all branches one by one just only to get their titles, which will hit the GitHub API limit and make listing slow

**Comment by ouuan** [comment]
What about putting all problems in the same branch :thinking:

**Comment by diauweb** [comment]
> What about putting all problems in the same branch

That will result in a same amount of query

**Comment by diauweb** [comment]
> > What about putting all problems in the same branch
> 
> That will result in a same amount of query

And it'll be terrible for someone want to edit a single problem. Testdatas are large
